compliance/urls.py
from django.conf.urls import url

from .views import ClientViews, BirViews, StatusViews, ComplianceViews, AttachmentViews

app_name = 'compliance'
urlpatterns = [
    # compliance home
    url(r'^$', ComplianceViews.index, name='index'),

    # clients
    url(r'^engagements$', ClientViews.index, name='client_index'),
    url(r'^engagements/(?P<id>[0-9]+)/$', ClientViews.detail, name='client_detail'),
    url(r'^engagements/(?P<id>[0-9]+)/update/', ClientViews.update, name='client_update'),
    url(r'^engagements/new/(?P<id>[0-9]+)*$', ClientViews.new, name='client_new'),
    url(r'^engagements/create/', ClientViews.create, name='client_create'),
    url(r'^engagements/(?P<id>[0-9]+)/delete/$', ClientViews.destroy, name='client_destroy'),
    url(r'^engagements/(?P<id>[0-9]+)/deactivate/$', ClientViews.deactivate, name='client_deactivate'),
    url(r'^engagements/(?P<id>[0-9]+)/activate/$', ClientViews.activate, name='client_activate'),
    
    # bir
    url(r'^bir$', BirViews.index, name='bir_index'),
    url(r'^bir/(?P<id>[0-9]+)/delete/$', BirViews.destroy, name='bir_destroy'),
    
    #  status
    url(r'^status$', StatusViews.index, name='status_index'),
    url(r'^status/(?P<id>[0-9]+)/$', StatusViews.detail, name='status_detail'),
    url(r'^status/(?P<id>[0-9]+)/update/', StatusViews.update, name='status_update'),
    url(r'^status/new$', StatusViews.new, name='status_new'),
    url(r'^status/create/', StatusViews.create, name='status_create'),
    url(r'^status/(?P<id>[0-9]+)/delete/$', StatusViews.destroy, name='status_destroy'),
    
    #  attachments
    url(r'^attachments/(?P<client_id>[0-9]+)/$', AttachmentViews.index, name='attachment_index'),
    url(r'^attachments/new/(?P<client_id>[0-9]+)*$', AttachmentViews.new, name='attachment_new'),
    url(r'^attachments/create/', AttachmentViews.create, name='attachment_create'),
    url(r'^attachments/(?P<id>[0-9]+)/delete/$', AttachmentViews.destroy, name='attachment_destroy'),
    
]

dtr/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views
from .models import Timetable, Schedule, ScheduleTimetable, Log, Attendance, AttendanceLog, GraceLateIn
from .forms import TimetableForm, ScheduleForm, LogForm, AttendanceForm, AttendanceLogFormSet, GraceLateInForm


class TimetableVars():
    context_search_placeholder = 'type remarks'
    model = Timetable
    model_name = 'timetable'
    model_app = 'dtr'
    model_order_by = ('time_in', 'time_out')

    model_url_index = 'dtr:timetable_index'
    model_url_detail = 'dtr:timetable_detail'
    model_url_new = 'dtr:timetable_new'
    model_url_create = 'dtr:timetable_create'
    model_url_update = 'dtr:timetable_update'
    model_url_destroy = 'dtr:timetable_destroy'

    model_template_index = 'dtr/timetables/index.html'
    model_template_new = 'dtr/timetables/new.html'
    model_template_detail = 'dtr/timetables/detail.html'

    model_form = TimetableForm


class ScheduleVars():
    context_search_placeholder = 'type employee abbr/lastname'
    model = Schedule
    model_name = 'schedule'
    model_name_plural = 'schedules'
    model_app = 'dtr'
    model_order_by = ('date', 'employee')

    model_url_index = 'dtr:' + model_name + '_index'
    model_url_detail = 'dtr:' + model_name + '_detail'
    model_url_new = 'dtr:' + model_name + '_new'
    model_url_create = 'dtr:' + model_name + '_create'
    model_url_update = 'dtr:' + model_name + '_update'
    model_url_destroy = 'dtr:' + model_name + '_destroy'

    model_template_index = 'dtr/' + model_name_plural + '/index.html'
    model_template_new = 'dtr/' + model_name_plural + '/new.html'
    model_template_detail = 'dtr/' + model_name_plural + '/detail.html'

    model_form = ScheduleForm


class LogVars():
    context_search_placeholder = 'type employee abbr/lastname'
    model = Log
    model_name = 'log'
    model_name_plural = 'logs'
    model_app = 'dtr'
    model_order_by = ('date_time', 'employee', 'id')

    model_url_index = 'dtr:' + model_name + '_index'
    model_url_detail = 'dtr:' + model_name + '_detail'
    model_url_new = 'dtr:' + model_name + '_new'
    model_url_create = 'dtr:' + model_name + '_create'
    model_url_update = 'dtr:' + model_name + '_update'
    model_url_destroy = 'dtr:' + model_name + '_destroy'

    model_template_index = 'dtr/' + model_name_plural + '/index.html'
    model_template_new = 'dtr/' + model_name_plural + '/new.html'
    model_template_detail = 'dtr/' + model_name_plural + '/detail.html'

    model_form = LogForm


class AttendanceVars():
    context_search_placeholder = 'type employee abbr/lastname'
    model = Attendance
    model_name = 'attendance'
    model_name_plural = 'attendance'
    model_app = 'dtr'
    model_order_by = ('date', 'employee')

    model_url_index = 'dtr:' + model_name + '_index'
    model_url_detail = 'dtr:' + model_name + '_detail'
    model_url_new = 'dtr:' + model_name + '_new'
    model_url_create = 'dtr:' + model_name + '_create'
    model_url_update = 'dtr:' + model_name + '_update'
    model_url_destroy = 'dtr:' + model_name + '_destroy'

    model_template_index = 'dtr/' + model_name_plural + '/index.html'
    model_template_new = 'dtr/' + model_name_plural + '/new.html'
    model_template_detail = 'dtr/' + model_name_plural + '/detail.html'

    model_form = AttendanceForm


class GraceLateInVars():
    context_search_placeholder = 'type alias/remarks'
    model = GraceLateIn
    model_name = 'gracelatein'
    model_name_plural = 'gracelateins'
    model_app = 'dtr'
    model_order_by = ('id')

    model_url_index = 'dtr:' + model_name + '_index'
    model_url_detail = 'dtr:' + model_name + '_detail'
    model_url_new = 'dtr:' + model_name + '_new'
    model_url_create = 'dtr:' + model_name + '_create'
    model_url_update = 'dtr:' + model_name + '_update'
    model_url_destroy = 'dtr:' + model_name + '_destroy'

    model_template_index = 'dtr/' + model_name_plural + '/index.html'
    model_template_new = 'dtr/' + model_name_plural + '/new.html'
    model_template_detail = 'dtr/' + model_name_plural + '/detail.html'

    model_form = GraceLateInForm
        

app_name = 'dtr'
urlpatterns = [
    url(r'^$', views.DTRViews.index, name='index'),
    url(r'^process-dtr$', views.DTRViews.dtr, name='process_dtr'),

    url(r'^timetables$', views.TimetableViews.index, {'model_vars': TimetableVars}, name='timetable_index'),
    url(r'^timetables/(?P<id>[0-9]+)/$', views.TimetableViews.detail, {'model_vars': TimetableVars}, name='timetable_detail'),
    url(r'^timetables/(?P<id>[0-9]+)/update/', views.TimetableViews.update, {'model_vars': TimetableVars}, name='timetable_update'),
    url(r'^timetables/new/(?P<id>[0-9]+)*$', views.TimetableViews.new, {'model_vars': TimetableVars}, name='timetable_new'),
    url(r'^timetables/create/', views.TimetableViews.create, {'model_vars': TimetableVars}, name='timetable_create'),
    url(r'^timetables/(?P<id>[0-9]+)/delete/$', views.TimetableViews.destroy, {'model_vars': TimetableVars}, name='timetable_destroy'),

    url(r'^schedules$', views.ScheduleViews.index, {'model_vars': ScheduleVars}, name='schedule_index'),
    url(r'^schedules/(?P<id>[0-9]+)/$', views.ScheduleViews.detail, {'model_vars': ScheduleVars}, name='schedule_detail'),
    url(r'^schedules/(?P<id>[0-9]+)/update/', views.ScheduleViews.update, {'model_vars': ScheduleVars}, name='schedule_update'),
    url(r'^schedules/new/(?P<id>[0-9]+)*$', views.ScheduleViews.new, {'model_vars': ScheduleVars}, name='schedule_new'),
    url(r'^schedules/create/', views.ScheduleViews.create, {'model_vars': ScheduleVars}, name='schedule_create'),
    url(r'^schedules/(?P<id>[0-9]+)/delete/$', views.ScheduleViews.destroy, {'model_vars': ScheduleVars}, name='schedule_destroy'),

    url(r'^logs$', views.LogViews.index, {'model_vars': LogVars}, name='log_index'),
    url(r'^logs/(?P<id>[0-9]+)/$', views.LogViews.detail, {'model_vars': LogVars}, name='log_detail'),
    url(r'^logs/(?P<id>[0-9]+)/update/', views.LogViews.update, {'model_vars': LogVars}, name='log_update'),
    url(r'^logs/new/(?P<id>[0-9]+)*$', views.LogViews.new, {'model_vars': LogVars}, name='log_new'),
    url(r'^logs/create/', views.LogViews.create, {'model_vars': LogVars}, name='log_create'),
    url(r'^logs/(?P<id>[0-9]+)/delete/$', views.LogViews.destroy, {'model_vars': LogVars}, name='log_destroy'),

    url(r'^attendance$', views.AttendanceViews.index, {'model_vars': AttendanceVars}, name='attendance_index'),
    url(r'^attendance/(?P<id>[0-9]+)/$', views.AttendanceViews.detail, {'model_vars': AttendanceVars}, name='attendance_detail'),
    url(r'^attendance/(?P<id>[0-9]+)/update/', views.AttendanceViews.update, {'model_vars': AttendanceVars}, name='attendance_update'),
    url(r'^attendance/new/(?P<id>[0-9]+)*$', views.AttendanceViews.new, {'model_vars': AttendanceVars}, name='attendance_new'),
    url(r'^attendance/create/', views.AttendanceViews.create, {'model_vars': AttendanceVars}, name='attendance_create'),
    url(r'^attendance/(?P<id>[0-9]+)/delete/$', views.AttendanceViews.destroy, {'model_vars': AttendanceVars}, name='attendance_destroy'),

    url(r'^grace$', views.GraceLateInViews.index, {'model_vars': GraceLateInVars}, name='gracelatein_index'),
    url(r'^grace/(?P<id>[0-9]+)/$', views.GraceLateInViews.detail, {'model_vars': GraceLateInVars}, name='gracelatein_detail'),
    url(r'^grace/(?P<id>[0-9]+)/update/', views.GraceLateInViews.update, {'model_vars': GraceLateInVars}, name='gracelatein_update'),
    url(r'^grace/new/(?P<id>[0-9]+)*$', views.GraceLateInViews.new, {'model_vars': GraceLateInVars}, name='gracelatein_new'),
    url(r'^grace/create/', views.GraceLateInViews.create, {'model_vars': GraceLateInVars}, name='gracelatein_create'),
    url(r'^grace/(?P<id>[0-9]+)/delete/$', views.GraceLateInViews.destroy, {'model_vars': GraceLateInVars}, name='gracelatein_destroy'),
]

santosCua/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# serving files in /media
from django.conf import settings
from django.conf.urls.static import static

# django-notifications
# https://github.com/django-notifications/django-notifications
import notifications.urls

from public.views import home

urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')), # admin docs
    url(r'^admin/', admin.site.urls, name='admin'),
    
    url(r'^contacts/', include('contacts.urls')),
    url(r'^employees/', include('employees.urls')),

    url(r'^compliance/', include('compliance.urls')),


    url(r'^payrollone/payroll/costcenters/', include('costcenters.urls')),
    url(r'^payrollone/hr/dtr/', include('dtr.urls')),
    url(r'^payrollone/hr/leave-management/', include('leaves.urls')),


    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    
    url(r'^home/', home),
    url(r'^', include('public.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bir/models.py
from django.db import models

# Create your models here.


class Rdo(models.Model):
    """docstring for ClassName"""
    code = models.CharField(max_length=3, blank=True)
    rdo = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.code


class BirForm(models.Model):
    """docstring for ClassName"""
    dpc_choices = [
        (1, 'monthly'),
        (2, 'quarterly'),
        (3, 'annually'),
        (4, 'custom'),
    ]

    dcr_choices = [
        (1, 'absolute'),
        (2, 'relative'),
    ]

    ddt_choices = [
        (1, 'fix'),
        (2, 'count'),
    ]

    form_code = models.CharField(max_length=10, null=False, blank=False, verbose_name='code')
    form = models.CharField(max_length=50, null=False, blank=False)
    description = models.CharField(max_length=250, null=True, blank=True)
    deadline_period = models.IntegerField(choices=dpc_choices, verbose_name='period', )
    deadline_cy_ref = models.IntegerField(choices=dcr_choices, verbose_name='bus. year ref', default=2)
    deadline_date_type = models.IntegerField(choices=ddt_choices, verbose_name='date type', default=1)

    def __str__(self):
        ret = str(self.form_code)
        return ret

    @property
    def dead_period(self):
        ret = self.deadline_period
        # get string value
        for choice in self.dpc_choices:
            if choice[0] == ret:
                ret = choice[1][0].upper()
                break

        return ret

    @property
    def dead_by_ref(self):
        ret = self.deadline_cy_ref
        # get string value
        for choice in self.dcr_choices:
            if choice[0] == ret:
                ret = choice[1][0].upper()
                break

        return ret

    @property
    def dead_date_type(self):
        ret = self.deadline_date_type
        # get string value
        for choice in self.ddt_choices:
            if choice[0] == ret:
                ret = choice[1][0].upper()
                break

        return ret


class BirFormSchedule(models.Model):
    """docstring for ClassName"""
    bir_form = models.ForeignKey(BirForm, related_name='schedules')
    index = models.IntegerField(null=False, blank=False)
    month = models.IntegerField(null=False, blank=False)
    day = models.IntegerField(null=False, blank=False)

compliance/forms.py
from django import forms

from .models import Client, ClientPractitioner, BirCompliance, ClientAttachment


class ClientForm(forms.ModelForm):
    """docstring for ContactForm"""
    class Meta:
        year_list = list(range(2009, 2031))
        
        model = Client
        exclude = ['practitioners']
        widgets = {
            'date_start': forms.SelectDateWidget(years=year_list),
            'date_end': forms.SelectDateWidget(years=year_list),
        }

PractitionerFormSet = forms.inlineformset_factory(
    Client,
    ClientPractitioner,
    fields=[
        'employee', 'date_assigned', 'date_transferred', 'remarks'
    ],
    extra=1,
)

BIRComplianceFormSet = forms.inlineformset_factory(
    Client,
    BirCompliance,
    fields=[
        'bir_form', 'is_active',
    ],
    extra=1,
    can_delete=False,
)

class ClientAttachmentForm(forms.ModelForm):
    """docstring for ContactForm"""
    class Meta:
        
        model = ClientAttachment
        fields = '__all__'

compliance/templates/compliance/bir/index.html
{% extends "base_santoscua.html" %}

{% block title %}BIR Deadlines{% endblock title %}

{% block nav %}
    {% include '../home.html' %}
{% endblock nav %}

{% block head %}
    <style type="text/css">
        .model-icon{
            font-size: 40px;
            color: black;
        }
        .pager li.active > a, .pager li.active > span{
            color: #fff;
            background-color:#212121;
            border-color: #212121;
            pointer-events:none;
        }
        .actions-toggle-icons{
            font-size: 25px;
        }
    </style>
{% endblock head %}

{% block content %}
     <h1 class="">BIR Deadline - List</h1>

     {% include './includes/index_search.html' %}

     {% if not bir_list %}
        <div class="container">
            {% include 'includes/index_no_record.html' %}
            
        </div>
     {% endif %}

    {% if bir_list %}
        <!-- pagination top -->
        {% include 'includes/index_pagination.html' with model_list=bir_list model_name="bir deadlines" %}
        <!-- list -->
        <div class="container">
            <table class="table table-condensed table-bordered table-hover table-striped color-black">
                <thead class="table-inverse">
                    <tr class="text-capitalize ">
                        <th class="text-center " rowspan="2">date</th>
                        <th class="text-center " rowspan="2">compliance</th>
                        <th class="text-center " colspan="3">engagement</th>
                        <th class="text-center " rowspan="2">actions</th>
                    </tr>
                    <tr class="text-capitalize text-sm">
                        <th class="text-center ">ref#</th>
                        <th class="text-center ">client</th>
                        <th class="text-center ">assigned</th>
                    </tr>
                </thead>
                    {% for deadline in bir_list %}
                        <tr>
                            <!-- date -->
                            <td class="text-center ">
                                {{deadline.date_deadline}}
                            </td>

                            <!-- compliance -->
                            <td class="text-center ">
                                {{deadline.compliance.bir_form}}
                            </td>

                            <!-- engagement doc_ref -->
                            <td>
                                <a class="color-black" href="{% url 'compliance:client_detail' deadline.compliance.client.id%}">
                                    <u>{{deadline.compliance.client.doc_ref}}</u>
                                </a>
                            </td>

                            <!-- engagement client -->
                            <td>
                                {{deadline.compliance.client|title}}
                            </td>

                            <!-- engagement practitioner -->
                            <td class="text-center">
                                {{deadline.compliance.client.assigned.abbr|upper}}
                            </td>

                            <!-- actions -->
                            <td class="text-center">

                                <a class="btn btn-outline-default action-toggle-buttons" data-toggle="collapse" href="#id-table-actions-{{forloop.counter}}" aria-expanded="false" aria-controls="id-table-actions-{{forloop.counter}}">
                                  <i class="fa fa-angle-double-down actions-toggle-icons"></i>
                                </a>

                                <div class="collapse" id="id-table-actions-{{forloop.counter}}">
                                  <div class="card card-block">

                                    <form id='id-form-delete-{{forloop.counter}}' action="{% url 'compliance:bir_destroy' deadline.id %}" method="post">

                                        {% csrf_token %}
                                        <button form='id-form-delete-{{forloop.counter}}' class="action-delete btn btn-outline-danger" type="submit" title="delete">
                                            <i class="fa fa fa-trash-o" ></i>
                                        </button>
                                    </form> <!-- delete -->

                                  </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                <tbody>
                    
                </tbody>
            </table>

            <!-- pagination bootom -->
        {% include 'includes/index_pagination.html' with model_list=bir_list model_name="bir deadlines" %}
        </div>
    {% endif %}
    

{% endblock content %}

{% block script %}
    <script type="text/javascript">
        $(document).ready(function(){
            $('.action-deactivate').click(function(e){
                if (!confirm('Deactivate?')) {
                    e.preventDefault()
                    return
                }
            })

            $('.action-activate').click(function(e){
                if (!confirm('Activate?')) {
                    e.preventDefault()
                    return
                }
            })

            $('.action-toggle-buttons').click(function(){
                $(this).toggle()
            })
        })
    </script>
{% endblock script %}