costcenters/urls.py
from django.conf.urls import url

from . import views
from .models import Holiday
from .forms import HolidayForm


class HolidayVars():


    context_search_placeholder = 'soon'
    model = Holiday
    model_name = 'holiday'
    model_name_plural = 'holidays'
    model_app = 'costcenters'
    model_order_by = ('date')

    model_url_index = model_app + ':' + model_name + '_index'
    model_url_detail = model_app + ':' + model_name + '_detail'
    model_url_new = model_app + ':' + model_name + '_new'
    model_url_create = model_app + ':' + model_name + '_create'
    model_url_update = model_app + ':' + model_name + '_update'
    model_url_destroy = model_app + ':' + model_name + '_destroy'

    model_template_index = model_app + '/' + model_name_plural + '/index.html'
    model_template_new = model_app + '/' + model_name_plural + '/new.html'
    model_template_detail = model_app + '/' + model_name_plural + '/detail.html'

    model_form = HolidayForm

    
app_name = 'costcenters'
urlpatterns = [
    url(r'^$', views.CostCenterViews.index, name='index'),

    url(r'^branches$', views.BranchViews.index, name='branch_index'),
    url(r'^branches/(?P<id>[0-9]+)/$', views.BranchViews.detail, name='branch_detail'),
    url(r'^branches/(?P<id>[0-9]+)/update/', views.BranchViews.update, name='branch_update'),
    url(r'^branches/new/(?P<id>[0-9]+)*$', views.BranchViews.new, name='branch_new'),
    url(r'^branches/create/', views.BranchViews.create, name='branch_create'),
    url(r'^branches/(?P<id>[0-9]+)/delete/$', views.BranchViews.destroy, name='branch_destroy'),

    url(r'^projects$', views.ProjectViews.index, name='project_index'),
    url(r'^projects/(?P<id>[0-9]+)/$', views.ProjectViews.detail, name='project_detail'),
    url(r'^projects/(?P<id>[0-9]+)/update/', views.ProjectViews.update, name='project_update'),
    url(r'^projects/new/(?P<id>[0-9]+)*$', views.ProjectViews.new, name='project_new'),
    url(r'^projects/create/', views.ProjectViews.create, name='project_create'),
    url(r'^projects/(?P<id>[0-9]+)/delete/$', views.ProjectViews.destroy, name='project_destroy'),

    url(r'^works$', views.WorkViews.index, name='work_index'),
    url(r'^works/(?P<id>[0-9]+)/$', views.WorkViews.detail, name='work_detail'),
    url(r'^works/(?P<id>[0-9]+)/update/', views.WorkViews.update, name='work_update'),
    url(r'^works/new/(?P<id>[0-9]+)*$', views.WorkViews.new, name='work_new'),
    url(r'^works/create/', views.WorkViews.create, name='work_create'),
    url(r'^works/(?P<id>[0-9]+)/delete/$', views.WorkViews.destroy, name='work_destroy'),

    url(r'^holidays$', views.HolidayView.index, {'model_vars': HolidayVars}, name='holiday_index'),
    url(r'^holidays/(?P<id>[0-9]+)/$', views.HolidayView.detail, {'model_vars': HolidayVars}, name='holiday_detail'),
    url(r'^holidays/(?P<id>[0-9]+)/update/', views.HolidayView.update, {'model_vars': HolidayVars}, name='holiday_update'),
    url(r'^holidays/new/(?P<id>[0-9]+)*$', views.HolidayView.new, {'model_vars': HolidayVars}, name='holiday_new'),
    url(r'^holidays/create/', views.HolidayView.create, {'model_vars': HolidayVars}, name='holiday_create'),
    url(r'^holidays/(?P<id>[0-9]+)/delete/$', views.HolidayView.destroy, {'model_vars': HolidayVars}, name='holiday_destroy'),
]

dtr/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views
from .models import Timetable, Schedule, ScheduleTimetable, Log, Attendance, AttendanceLog, GraceLateIn
from .forms import TimetableForm, ScheduleForm, LogForm, AttendanceForm, AttendanceLogFormSet, GraceLateInForm


class TimetableVars():
    context_search_placeholder = 'type remarks'
    model = Timetable
    model_name = 'timetable'
    model_app = 'dtr'
    model_order_by = ('time_in', 'time_out')

    model_url_index = 'dtr:timetable_index'
    model_url_detail = 'dtr:timetable_detail'
    model_url_new = 'dtr:timetable_new'
    model_url_create = 'dtr:timetable_create'
    model_url_update = 'dtr:timetable_update'
    model_url_destroy = 'dtr:timetable_destroy'

    model_template_index = 'dtr/timetables/index.html'
    model_template_new = 'dtr/timetables/new.html'
    model_template_detail = 'dtr/timetables/detail.html'

    model_form = TimetableForm


class ScheduleVars():
    context_search_placeholder = 'type employee abbr/lastname'
    model = Schedule
    model_name = 'schedule'
    model_name_plural = 'schedules'
    model_app = 'dtr'
    model_order_by = ('date', 'employee')

    model_url_index = 'dtr:' + model_name + '_index'
    model_url_detail = 'dtr:' + model_name + '_detail'
    model_url_new = 'dtr:' + model_name + '_new'
    model_url_create = 'dtr:' + model_name + '_create'
    model_url_update = 'dtr:' + model_name + '_update'
    model_url_destroy = 'dtr:' + model_name + '_destroy'

    model_template_index = 'dtr/' + model_name_plural + '/index.html'
    model_template_new = 'dtr/' + model_name_plural + '/new.html'
    model_template_detail = 'dtr/' + model_name_plural + '/detail.html'

    model_form = ScheduleForm


class LogVars():
    context_search_placeholder = 'type employee abbr/lastname'
    model = Log
    model_name = 'log'
    model_name_plural = 'logs'
    model_app = 'dtr'
    model_order_by = ('date_time', 'employee', 'id')

    model_url_index = 'dtr:' + model_name + '_index'
    model_url_detail = 'dtr:' + model_name + '_detail'
    model_url_new = 'dtr:' + model_name + '_new'
    model_url_create = 'dtr:' + model_name + '_create'
    model_url_update = 'dtr:' + model_name + '_update'
    model_url_destroy = 'dtr:' + model_name + '_destroy'

    model_template_index = 'dtr/' + model_name_plural + '/index.html'
    model_template_new = 'dtr/' + model_name_plural + '/new.html'
    model_template_detail = 'dtr/' + model_name_plural + '/detail.html'

    model_form = LogForm


class AttendanceVars():
    context_search_placeholder = 'type employee abbr/lastname'
    model = Attendance
    model_name = 'attendance'
    model_name_plural = 'attendance'
    model_app = 'dtr'
    model_order_by = ('date', 'employee')

    model_url_index = 'dtr:' + model_name + '_index'
    model_url_detail = 'dtr:' + model_name + '_detail'
    model_url_new = 'dtr:' + model_name + '_new'
    model_url_create = 'dtr:' + model_name + '_create'
    model_url_update = 'dtr:' + model_name + '_update'
    model_url_destroy = 'dtr:' + model_name + '_destroy'

    model_template_index = 'dtr/' + model_name_plural + '/index.html'
    model_template_new = 'dtr/' + model_name_plural + '/new.html'
    model_template_detail = 'dtr/' + model_name_plural + '/detail.html'

    model_form = AttendanceForm


class GraceLateInVars():
    context_search_placeholder = 'type alias/remarks'
    model = GraceLateIn
    model_name = 'gracelatein'
    model_name_plural = 'gracelateins'
    model_app = 'dtr'
    model_order_by = ('id')

    model_url_index = 'dtr:' + model_name + '_index'
    model_url_detail = 'dtr:' + model_name + '_detail'
    model_url_new = 'dtr:' + model_name + '_new'
    model_url_create = 'dtr:' + model_name + '_create'
    model_url_update = 'dtr:' + model_name + '_update'
    model_url_destroy = 'dtr:' + model_name + '_destroy'

    model_template_index = 'dtr/' + model_name_plural + '/index.html'
    model_template_new = 'dtr/' + model_name_plural + '/new.html'
    model_template_detail = 'dtr/' + model_name_plural + '/detail.html'

    model_form = GraceLateInForm
        

app_name = 'dtr'
urlpatterns = [
    url(r'^$', views.DTRViews.index, name='index'),
    url(r'^process-dtr$', views.DTRViews.dtr, name='process_dtr'),

    url(r'^timetables$', views.TimetableViews.index, {'model_vars': TimetableVars}, name='timetable_index'),
    url(r'^timetables/(?P<id>[0-9]+)/$', views.TimetableViews.detail, {'model_vars': TimetableVars}, name='timetable_detail'),
    url(r'^timetables/(?P<id>[0-9]+)/update/', views.TimetableViews.update, {'model_vars': TimetableVars}, name='timetable_update'),
    url(r'^timetables/new/(?P<id>[0-9]+)*$', views.TimetableViews.new, {'model_vars': TimetableVars}, name='timetable_new'),
    url(r'^timetables/create/', views.TimetableViews.create, {'model_vars': TimetableVars}, name='timetable_create'),
    url(r'^timetables/(?P<id>[0-9]+)/delete/$', views.TimetableViews.destroy, {'model_vars': TimetableVars}, name='timetable_destroy'),

    url(r'^schedules$', views.ScheduleViews.index, {'model_vars': ScheduleVars}, name='schedule_index'),
    url(r'^schedules/(?P<id>[0-9]+)/$', views.ScheduleViews.detail, {'model_vars': ScheduleVars}, name='schedule_detail'),
    url(r'^schedules/(?P<id>[0-9]+)/update/', views.ScheduleViews.update, {'model_vars': ScheduleVars}, name='schedule_update'),
    url(r'^schedules/new/(?P<id>[0-9]+)*$', views.ScheduleViews.new, {'model_vars': ScheduleVars}, name='schedule_new'),
    url(r'^schedules/create/', views.ScheduleViews.create, {'model_vars': ScheduleVars}, name='schedule_create'),
    url(r'^schedules/(?P<id>[0-9]+)/delete/$', views.ScheduleViews.destroy, {'model_vars': ScheduleVars}, name='schedule_destroy'),

    url(r'^logs$', views.LogViews.index, {'model_vars': LogVars}, name='log_index'),
    url(r'^logs/(?P<id>[0-9]+)/$', views.LogViews.detail, {'model_vars': LogVars}, name='log_detail'),
    url(r'^logs/(?P<id>[0-9]+)/update/', views.LogViews.update, {'model_vars': LogVars}, name='log_update'),
    url(r'^logs/new/(?P<id>[0-9]+)*$', views.LogViews.new, {'model_vars': LogVars}, name='log_new'),
    url(r'^logs/create/', views.LogViews.create, {'model_vars': LogVars}, name='log_create'),
    url(r'^logs/(?P<id>[0-9]+)/delete/$', views.LogViews.destroy, {'model_vars': LogVars}, name='log_destroy'),

    url(r'^attendance$', views.AttendanceViews.index, {'model_vars': AttendanceVars}, name='attendance_index'),
    url(r'^attendance/(?P<id>[0-9]+)/$', views.AttendanceViews.detail, {'model_vars': AttendanceVars}, name='attendance_detail'),
    url(r'^attendance/(?P<id>[0-9]+)/update/', views.AttendanceViews.update, {'model_vars': AttendanceVars}, name='attendance_update'),
    url(r'^attendance/new/(?P<id>[0-9]+)*$', views.AttendanceViews.new, {'model_vars': AttendanceVars}, name='attendance_new'),
    url(r'^attendance/create/', views.AttendanceViews.create, {'model_vars': AttendanceVars}, name='attendance_create'),
    url(r'^attendance/(?P<id>[0-9]+)/delete/$', views.AttendanceViews.destroy, {'model_vars': AttendanceVars}, name='attendance_destroy'),

    url(r'^grace$', views.GraceLateInViews.index, {'model_vars': GraceLateInVars}, name='gracelatein_index'),
    url(r'^grace/(?P<id>[0-9]+)/$', views.GraceLateInViews.detail, {'model_vars': GraceLateInVars}, name='gracelatein_detail'),
    url(r'^grace/(?P<id>[0-9]+)/update/', views.GraceLateInViews.update, {'model_vars': GraceLateInVars}, name='gracelatein_update'),
    url(r'^grace/new/(?P<id>[0-9]+)*$', views.GraceLateInViews.new, {'model_vars': GraceLateInVars}, name='gracelatein_new'),
    url(r'^grace/create/', views.GraceLateInViews.create, {'model_vars': GraceLateInVars}, name='gracelatein_create'),
    url(r'^grace/(?P<id>[0-9]+)/delete/$', views.GraceLateInViews.destroy, {'model_vars': GraceLateInVars}, name='gracelatein_destroy'),
]

santosCua/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# serving files in /media
from django.conf import settings
from django.conf.urls.static import static

# django-notifications
# https://github.com/django-notifications/django-notifications
import notifications.urls

from public.views import home

urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')), # admin docs
    url(r'^admin/', admin.site.urls, name='admin'),
    
    url(r'^contacts/', include('contacts.urls')),
    url(r'^employees/', include('employees.urls')),

    url(r'^compliance/', include('compliance.urls')),


    url(r'^payrollone/payroll/costcenters/', include('costcenters.urls')),
    url(r'^payrollone/hr/dtr/', include('dtr.urls')),
    url(r'^payrollone/hr/leave-management/', include('leaves.urls')),


    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    
    url(r'^home/', home),
    url(r'^', include('public.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

costcenters/models.py
from django.db import models

from contacts.models import Contact
from employees.models import Employee
from public.models import City

# Create your models here.
class Branch(models.Model):
	parent = models.ForeignKey('self', null=True, blank=True, related_name='branches')
	contact = models.OneToOneField(Contact, null=True, blank=True)
	alias = models.CharField(max_length=50, null=True, blank=True)
	is_deleted = models.BooleanField(default=False)
	city = models.ForeignKey(City, default=1)
	employees = models.ManyToManyField(Employee)

	class Meta:
		verbose_name_plural = 'Branches'

	def __str__(self):
		if self.parent:
			return ' | '.join([str(self.parent), str(self.alias)])
		else:
			return str(self.alias)


class Project(models.Model):
	parent = models.ForeignKey('self', null=True, blank=True, related_name='sub_projects')
	branch = models.ForeignKey(Branch, null=True, blank=True, related_name='projects')
	contact = models.OneToOneField(Contact, null=True, blank=True)
	alias = models.CharField(max_length=50)
	remarks = models.CharField(max_length=100, null=True, blank=True)
	is_deleted = models.BooleanField(default=False)
	
	def __str__(self):
		return self.alias

	@property
	def is_sub_project(self):
		if self.parent:
			ret = True
		else:
			ret = False
		return ret


class Work(models.Model):
	work_name = models.CharField(max_length=50, verbose_name='name')
	description = models.CharField(max_length=100)
	is_deleted = models.BooleanField(default=False)
	
	def __str__(self):
		return self.work_name


class Holiday(models.Model):

    
    holiday_type_choices = [
        (1, 'Regular'),
        (2, 'Special'),
        (3, 'Special Working'),
        (4, 'Others')
    ]

    date = models.DateField()    
    cities = models.ManyToManyField(City)
    holiday = models.CharField(max_length=50)
    holiday_type = models.IntegerField(choices=holiday_type_choices)

    pay_on_absent = models.IntegerField(default=100)
    
    pay_premium_normal = models.IntegerField(default=100)
    cola_premium_normal = models.IntegerField(default=100)
    ot_premium_normal = models.IntegerField(default=60)
    pay_premium_rest = models.IntegerField(default=60)
    ot_premium_rest = models.IntegerField(default=18)

    def __str__(self):
        return ' - '.join([self.holiday, str(self.date)])

employees/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

from contacts.models import Contact

# Create your models here.

class Employee(models.Model):
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE, verbose_name='Name')
    id_num = models.CharField(max_length=30, unique=True, null=True, blank=True)
    abbr = models.CharField(max_length=5, unique=True, null=True, blank=True)
    date_hired = models.DateField(default=timezone.now)
    date_resigned = models.DateField(null=True, blank=True)
    is_deleted = models.BooleanField(default=False)

    # 2017-11-29
    user = models.OneToOneField(User, null=True, related_name='employee')
    supervisors = models.ForeignKey('self', null=True, related_name='sups')

    def __str__(self):
        # employees full name
        return self.contact.full_name

    @property
    def is_resigned(self, verbose_name='resigned'):
        ret = False
        return ret


class Salary(models.Model):

    payroll_type_choices = [
        (1, 'Daily'),
        (2, 'Periodic'),
    ]

    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, verbose_name='Name', related_name='salaries')
    date_start = models.DateField(default=timezone.now)
    date_end = models.DateField(null=True, blank=True)
    payroll_type = models.IntegerField(
        default = 2,
        choices=payroll_type_choices,
    )
    # monthly_work_days_ave = models.IntegerField(default=26)
    monthly_rate = models.DecimalField(max_digits=8, decimal_places=2)
    daily_rate = models.DecimalField(max_digits=8, decimal_places=2)
    hourly_rate = models.DecimalField(max_digits=8, decimal_places=2)

    @property
    def get_payroll_type(self):
        for payroll_type in self.payroll_type_choices:
            if payroll_type[0] == self.payroll_type:
                ret = payroll_type[1]
                break
        return ret

costcenters/forms.py
from django import forms

from .models import Branch, Project, Work, Holiday
from contacts.models import Contact


class BranchForm(forms.ModelForm):
    """docstring for ContactForm"""
    class Meta:
        model = Branch
        exclude = []


class ProjectForm(forms.ModelForm):
    """docstring for ContactForm"""
    class Meta:
        model = Project
        exclude = []


class WorkForm(forms.ModelForm):
    """docstring for ContactForm"""
    class Meta:
        model = Work
        exclude = []


class HolidayForm(forms.ModelForm):
    """docstring for ContactForm"""
    class Meta:
        model = Holiday
        exclude = []

costcenters/templates/costcenters/projects/detail.html
{% extends "base_santoscua.html" %}

{% load static %}

{% block title %}{{ record.alias|upper }} Project - Cost Center {% endblock title %}

{% block nav %}
    {{ block.super }}

    <!-- list -->
    <a class="nav-item nav-link text-white" href="{% url 'costcenters:project_index' %}">
        <i class="fa fa-2x fa-list-ul" title="Branches"></i>
    </a>

    <!-- delete -->
    <a class="nav-item nav-link text-white" href="{% url 'costcenters:project_destroy' record.id %}">
        <i class="fa fa-2x fa-trash " title="Delete"></i>
    </a>
{% endblock nav %}

{% block head %}
    <style type="text/css">
        .avatar {
            border:2px solid #212121;
        }            
    </style>    
{% endblock head %}

{% block content %}
     <h1>C.C. Project- Detail</h1>

     {% if record.contact.image %}
        <img class="img-thumbnail avatar" src="{% get_media_prefix %}{{ record.contact.image }}" alt="image {{ record.contact }}" width="150px" height="200px">
     {% endif %}
                                
    {% if not record.contact.image %}
        <img class="img-thumbnail avatar" src="/media/contacts/images/empty.png" alt="{{ record.contact }} has no image uploaded" width="200px" height="200px">
                                        
    {% endif %}

    <form enctype="multipart/form-data" action="{% url 'costcenters:project_update' record.id %}" method="post" class="form">
        {% csrf_token %}

        <div class="panel-group">
            <div class="panel panel-default">
                <a data-toggle="collapse" href="#id-div-project" aria-expanded="true">
                    <div class="panel-heading bg-inverse color-gray">
                        <h4 class="panel-title">
                            Project Info
                        </h4>
                    </div>
                    
                </a>
            <div id="id-div-project" aria-expanded="true" class="collapse show" >
                <div class="panel-body">
                    <table class="table table-condensed table-bordered" id="id-table-project">
                        <tbody>
                            {{ form.as_table|lower }}
                        </tbody>
                    </table>
                </div>
            </div>
            </div>
        </div>

        <!-- submit button -->
        <input class="action-save btn-success btn-block border-5" type="submit" name="save" value="Save" id='id-bottom'>
        <input class="action-save btn-success btn-block border-5" type="submit" name="saveandcontinue" value="Save and continue editing">
    </form>
{% endblock content %}

{% block script %}
    <script type="text/javascript">
        $(document).ready(function(){
            
        })
    </script>
{% endblock script %}

costcenters/templates/costcenters/projects/index.html
{% extends "base_santoscua.html" %}

{% load  humanize %}

{% block title %}Projects - Cost Centers{% endblock title %}

{% block nav %}
    {{ block.super }}

    <!-- new -->
    <a class="nav-item nav-link" href="{% url 'costcenters:project_new' %}">
        <i class="fa fa-2x fa-plus text-white" title="New"></i>
    </a>

{% endblock nav %}

{% block head %}
    <style type="text/css">
        .model-icon{
            font-size: 40px;
            color: black;
        }
        .pager li.active > a, .pager li.active > span{
            color: #fff;
            background-color:#212121;
            border-color: #212121;
            pointer-events:none;
        }
        .img-avatar {
            min-width: 150px;
            min-height: 200px;
        }
    </style>
{% endblock head %}

{% block content %}
    
    <h1 class="">Cost Center Projects - List</h1>
    <!-- search box -->
    {% include 'includes/index_search.html' %}


        <div class="container">
        {% if model_list %}
            <!-- pagination top -->
            {% include 'includes/index_pagination.html' with model_list=model_list model_name='projects' %}

            {# table list #}
            <div class="">
                <table class="table table-condensed table-bordered table-hover table-striped color-black">
                    <thead class="table-inverse">
                        <tr class="text-capitalize ">
                            <th class="text-center ">parent</th>
                            <th class="text-center ">project/sub-project</th>
                            <th class="text-center ">branch</th>
                            <th class="text-center ">address</th>
                            <th class="text-center ">actions</th>
                        </tr>
                    </thead>
                        {% for record in model_list %}
                            <tr>
                                <!-- parent -->
                                    {% if record.parent %}
                                    <td class="">
                                        <a href="{% url 'costcenters:project_detail' record.parent_id %}" target="_blank" title="view project parent detail">
                                        {{ record.parent.alias }}
                                        </a>
                                    </td>
                                    {% endif %}

                                    {% if not record.parent %}
                                    <td class="text-center">
                                        <i class="fa fa-times text-danger"></i>
                                    </td>
                                    {% endif %}

                                <!-- project/sub-project -->
                                <td class="text-center ">
                                    <a href="{% url 'costcenters:project_detail' record.id %}" target="_blank" title="view project detail">
                                    {{ record.alias }}
                                    </a>
                                </td>

                                <!-- branch -->
                                <td class="text-center ">
                                    {% if record.branch %}
                                        <a href="{% url 'costcenters:branch_detail' record.branch_id %}" target="_blank" title="view branch detail">
                                        {{ record.branch.alias }}
                                        </a>
                                    {% endif %}

                                    {% if not record.branch %}
                                        <a href="{% url 'costcenters:branch_detail' record.parent.branch_id %}" target="_blank" title="view branch detail">
                                        {{ record.parent.branch.alias }}
                                        </a>
                                    {% endif %}
                                </td>

                                <!-- address -->
                                <td class="text-left ">
                                    address soon to rise
                                </td>

                                <!-- actions -->
                                <td class="text-center">

                                    <a class="btn btn-outline-default action-toggle-buttons" data-toggle="collapse" href="#id-table-actions-{{forloop.counter}}" aria-expanded="false" aria-controls="id-table-actions-{{forloop.counter}}">
                                      <i class="fa fa-angle-double-down actions-toggle-icons"></i>
                                    </a>

                                    <div class="collapse" id="id-table-actions-{{forloop.counter}}">
                                      <div class="card card-block">

                                        <form id='id-form-delete-{{forloop.counter}}' action="{% url 'costcenters:project_destroy' record.id %}" method="post">

                                            {% csrf_token %}
                                            <button form='id-form-delete-{{forloop.counter}}' class="action-delete btn btn-outline-danger" type="submit" title="delete">
                                                <i class="fa fa fa-trash-o" ></i>
                                            </button>
                                        </form> <!-- delete -->

                                      </div>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    <tbody>
                        
                    </tbody>
                </table>
            </div>

            <!-- pagination bottom --> 
            {% include 'includes/index_pagination.html' with model_list=model_list model_name='branches' %}
        {% endif %}
        
        <!-- if recordset is blank -->
        {% if not model_list  %}
            {% include 'includes/index_no_record.html' %}
        {% endif %}
        </div>


{% endblock content %}

{% block script %}
    <script type="text/javascript">
        $(document).ready(function(){

            $('.action-toggle-buttons').click(function(){
                $(this).toggle()
            })
        })
    </script>
{% endblock script %}

costcenters/templates/costcenters/projects/new.html
{% extends "base_santoscua.html" %}

{% load static %}

{% block title %}Cost Center Projects - New{% endblock title %}

{% block nav %}
    {{ block.super }}
    <!-- list -->
    <a class="nav-item nav-link" href="{% url 'costcenters:project_index' %}">
        <i class="fa fa-2x fa-list-ul text-default" title="Projects"></i>
    </a>
{% endblock nav %}

{% block content %}
    <h1>Create new C.C. Project</h1>

    <form enctype="multipart/form-data" action="{% url 'costcenters:project_create' %}" method="post">
        {% csrf_token %}
        
        <table class="table table-condensed table-bordered">
            <tbody>
                {{ form.as_table }}
            </tbody>
            
        </table>
        <input type="submit" value="Create">
    </form>
    
{% endblock content %}

{% block script %}
    <script type="text/javascript">
        $(document).ready(function(){
            
            // set focus
            // $('#id_id_num').focus()
        })
    </script>
{% endblock script %}